### ISSUE TITLE
Issue with Krastorio 2

### ISSUE THREAD

**Issue by stucker9** [ickputzdirwech/Shortcuts-ick#1]
Hello,
I am unable to craft the creep collector and the jackhammer in Krastorio 2 as your mod seems to replace the recipe with shortcuts for these items which is fine and all but the crafting of the collector or jackhammer is needed to use the shortcut :) Thanks if you can support that mod :)

**Comment by ickputzdirwech** [comment]
Hey, thanks for the report. I think I fixed it already quite a while ago in version 1.1.1 . There was a report on the mod portal about the same issue. Sorry for never replying here! If this issue persists for you or you have any other issue, please let me know.
