### ISSUE TITLE
Hide special tool items from Space Exploration

### ISSUE THREAD

**Issue by robot256** [ickputzdirwech/Shortcuts-ick#10]
There are several tool items added by Space Exploration that should only be accessible from Space Exploration GUIs.  Can they be hidden from the Shortcuts generator?  Looks like anything matching the regular expression `se%-*%-targeter` should be blacklisted unless explicitly added.

**Comment by ickputzdirwech** [comment]
Thanks for the report! Should be fixed in 1.1.24
