### ISSUE TITLE
My local copy of the mod for 2.0

### ISSUE THREAD

**Issue by JamieRCHI** [ickputzdirwech/Shortcuts-ick#16]
[Shortcuts-ick_2.0.1.zip](https://github.com/user-attachments/files/17526280/Shortcuts-ick_2.0.1.zip)

Also modified the icons for better visibility. (Just the Tr shortcut in your mod. The rest in the Factorio graphics shortcuts.)
https://steamcommunity.com/sharedfiles/filedetails/?id=3359721172

**Comment by ickputzdirwech** [comment]
Thanks!
