### ISSUE TITLE
Toggle Artillery cannon fire always changes the orientation of the artillery train towards the right

### ISSUE THREAD

**Issue by Agrrox** [ickputzdirwech/Shortcuts-ick#5]
**Toggle Artillery cannon fire** always changes the orientation of the artillery train towards the right.

before using shortcut:
![screenshot_1410468_1536x352](https://user-images.githubusercontent.com/10901821/148706676-fa2a58df-5124-4c6b-aabd-e62190380429.png)
after using shortcut:
![screenshot_1411514_1536x352](https://user-images.githubusercontent.com/10901821/148706682-82d39fb4-6a1a-4bb4-a100-dd76fa9477c9.png)

**Comment by ickputzdirwech** [comment]
Thanks for the report! This will be fixed in version 1.1.22 coming hopefully later this day.

**Comment by ickputzdirwech** [comment]
054d2934d5b03326791b2edafb778c2286dcf0c5

**Comment by ickputzdirwech** [comment]
f174d15b1619e1aa85b18ef193b84bd3f565e973
