### ISSUE TITLE
do not hide/remove equipment or remote controls by default

### ISSUE THREAD

**Issue by Agrrox** [ickputzdirwech/Shortcuts-ick#6]
Currently, the mod is hiding (removing) remote control items from player inventory and crafting menu.
I think this shouldn't be the default behavior of the mod, as this is invasive behavior to the vanilla game.

**Comment by ickputzdirwech** [comment]
Thanks for the suggestion, I won't do this however. For the following reasons: The mod is already invasive, as it essentially grants free items via the shortcuts. This is not the main point of the mod however. The idea is that players don't have to carry that many single-purpose items with them anymore. If I would disable this option by default, a lot of players would be annoyed that every time they use the shortcut they get another item in their inventory that they don't need and can't delete.
